### ISSUE TITLE
extension started causing segfaults

### ISSUE THREAD

**Issue by dadamssg** [10gen-labs/mongo-php-driver-prototype#1302]
### Bug Report

I have 3 servers running php with the mongo extensions installed. On Feb 13, all of them encountered the same error at the same time. The error being a segfault coming from libcrypto.so.1.0.2k.

The odd part(aside from all the servers experiencing the same thing at the same time) is that the code i'm running is not even using the mongo extension. We use JWT tokens for auth. This crash seems to come up only on api requests that are interacting with a crypto algorithm, to either encode or decode a JWT token. I disabled the mongo extension, restarted php-fpm, and things started working normally again. Thankfully i'm just using mongo to store xhprof profiles on demand but i have no idea what changed on all 3 of my servers at the same time to cause this.

In my debugging, i wrote a simple test script that generates a JWT token using the same library. i was able to run this script fine from the command line with the mongo extension enabled. It appears a magic combination of the following causes the error:

- php-fpm handling the request
- mongo extension being enabled
- php interacting with a crypto lib

I was able to make requests against my public api endpoints(that don't require any crypto) with the mongo extension enabled and those responded fine.

I develop in docker and i'm unable to reproduce the issue in my development container however i can still reproduce it in my actual servers.

### Environment

- Centos 7
- PHP v7.33.3
- mongodb extension 1.10.0(i've also tried updating to v1.12.0)
- OpenSSL 1.0.2k-fips  26 Jan 2017

```
$ php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php.d/mongodb.ini,
mongodb
libbson bundled version => 1.20.0
libmongoc bundled version => 1.20.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongoc compression zstd => disabled
libmongocrypt bundled version => 1.3.0
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => /srv/mongodebug => /srv/mongodebug
mongodb.mock_service_id => Off => Off

```

### Expected and Actual Behavior

![image](https://user-images.githubusercontent.com/881986/154080704-c5c4ede5-a7f7-4623-a25e-d7c7d730ce06.png)

### Debug Log

```
[root@server mongodebug]# cat PHONGO-1644934589G9Hllq
[2022-02-15T14:16:29.910968+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_get_distro():389
[2022-02-15T14:16:29.911028+00:00]     mongoc: TRACE   > ENTRY: _mongoc_linux_distro_scanner_read_key_value_file():154
[2022-02-15T14:16:29.911331+00:00]     mongoc: TRACE   > ENTRY: _process_line():93
[2022-02-15T14:16:29.911338+00:00]     mongoc: TRACE   > TRACE: _process_line():121 Found name: CentOS Linux
[2022-02-15T14:16:29.911341+00:00]     mongoc: TRACE   >  EXIT: _process_line():128
[2022-02-15T14:16:29.911344+00:00]     mongoc: TRACE   > ENTRY: _process_line():93
[2022-02-15T14:16:29.911346+00:00]     mongoc: TRACE   >  EXIT: _process_line():128
[2022-02-15T14:16:29.911349+00:00]     mongoc: TRACE   > ENTRY: _process_line():93
[2022-02-15T14:16:29.911352+00:00]     mongoc: TRACE   >  EXIT: _process_line():128
[2022-02-15T14:16:29.911354+00:00]     mongoc: TRACE   > ENTRY: _process_line():93
[2022-02-15T14:16:29.911357+00:00]     mongoc: TRACE   >  EXIT: _process_line():128
[2022-02-15T14:16:29.911360+00:00]     mongoc: TRACE   > ENTRY: _process_line():93
[2022-02-15T14:16:29.911363+00:00]     mongoc: TRACE   > TRACE: _process_line():125 Found version: 7
[2022-02-15T14:16:29.911366+00:00]     mongoc: TRACE   >  EXIT: _process_line():128
[2022-02-15T14:16:29.911381+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_read_key_value_file():205
[2022-02-15T14:16:29.911386+00:00]     mongoc: TRACE   >  EXIT: _mongoc_linux_distro_scanner_get_distro():398
```

**Comment by jmikola** [comment]
When FPM spawns a PHP worker process, PHP invokes the MINIT function of each enabled extension. For `ext-mongodb`, [`PHP_MINIT_FUNCTION(mongodb)`](https://github.com/mongodb/mongo-php-driver/blob/1.12.0/php_phongo.c#L3647) will be called. If we step through that and ignore the PHP-specific stuff (e.g. registering classes), we see two notable actions:

 * Calling `bson_mem_set_vtable` to instruct libbson and libmongoc to use PHP's [persistent memory allocation functions](https://www.phpinternalsbook.com/php7/memory_management/zend_memory_manager.html)
 * Calling `mongoc_init` to initialize libmongoc and its dependencies

Diving into libmongoc, [`mongoc_init`](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-init.c) delegates to [`_mongoc_do_init`](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-init.c#L95) with logic to ensure that function is only called once per process. When compiled against OpenSSL, 
`_mongoc_do_init` will call [`_mongoc_openssl_init`](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-openssl.c#L73) to initialize OpenSSL. I'll stop there for now, but let's remember that function as a future point of investigation for the various OpenSSL function calls that may conflict with whatever else is happening in your environment.

The debug log you provided is unfortunately not helpful here, as it's only reporting tracing from some of libmongoc's own function calls. Since you're not interacting with the driver in this request, the debug log is only reporting some functions that get called from `mongoc_init`. In this case, we see some trace logs from functions in [mongoc-linux-distro-scanner.c](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-linux-distro-scanner.c), which is called via [mongoc-handshake.c](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-handshake.c) (when `_mongoc_do_init` invokes [`_mongoc_handshake_init`](https://github.com/mongodb/mongo-c-driver/blob/1.20.0/src/libmongoc/src/mongoc/mongoc-init.c#L140)).

To investigate this further, I'll need a GDB backtrace of the segfault.

> In my debugging, i wrote a simple test script that generates a JWT token using the same library.

What does "same library" refer to in this case? I assume the "library" is a PHP package that interacts directly with [`ext-openssl`](https://www.php.net/openssl), but correct me if I'm mistaken.

If you're able to share that "simple test script" that also produces a segfault when run through FPM, that'd be most helpful. Sharing `composer.json` and `composer.lock` (if applicable) might also help.

> I develop in docker and i'm unable to reproduce the issue in my development container however i can still reproduce it in my actual servers.

What are the differences in software versions between your production environment and Docker container?

**Comment by dadamssg** [comment]
Wow, thank you for the quick response. 

The "same library" is referring to firebase's jwt package: `firebase/php-jwt@v5.2.1` [Link](https://github.com/firebase/php-jwt/tree/v5.2.1).

The "simple test script" just used the above package so echo out a encoded token. I ran that script from the command line and it ran fine so i don't think providing that will be helpful. It was essentially [the example](https://github.com/firebase/php-jwt/tree/v5.2.1#example) provided in the readme.

Here are some versions on dev server that i can reproduce the problem:
```
[root@server mongodebug]# php  --version
PHP 7.3.33 (cli) (built: Nov 16 2021 11:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33, Copyright (c) 1999-2018, by Zend Technologies

[root@servermongodebug]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

[root@server mongodebug]# pecl list
Installed packages, channel pecl.php.net:
=========================================
Package    Version State
apcu       5.1.21  stable
igbinary   3.2.7   stable
imagick    3.4.4   stable
mcrypt     1.0.4   stable
mongodb    1.12.0  stable
pdo_sqlsrv 5.9.0   stable
redis      4.3.0   stable
sqlsrv     5.9.0   stable
zip        1.20.0  stable
```

Here are the same versions of my container that i am unable to reproduce the issue:
```
[root@217275d42dfc /]# php -v
PHP 7.3.28 (cli) (built: Apr 27 2021 13:57:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

[root@217275d42dfc /]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

[root@217275d42dfc /]# pecl list
Installed packages, channel pecl.php.net:
=========================================
Package    Version State
imagick    3.4.4   stable
mcrypt     1.0.4   stable
mongodb    1.9.1   stable
pdo_sqlsrv 5.9.0   stable
redis      4.3.0   stable
sqlsrv     5.9.0   stable
xdebug     3.0.4   stable
zip        1.19.2  stable
```

I just attempted to produce a core file but i don't know what i'm doing:
```
ulimit -c unlimited
mkdir /srv/php-dump
chown nginx /srv/php-dump
echo "/srv/php-dump/core-%e.%p" > /proc/sys/kernel/core_pattern
cd /etc/php.d
mv mongodb.ini_bak mongodb.ini
service php-fpm restart

# triggered a failure
# checked in /srv/php-dump but it's empty
```

**Comment by jmikola** [comment]
You're definitely going to need debug headers for all libraries involved in the backtrace ("?? ()" is evidence that no debug symbols are available). That includes PHP itself, any relevant extensions, and OpenSSL. I not familiar with how [Remi's packages are compiled](https://blog.remirepo.net/), but with respect to `ext-mongodb` if you find that no debug symbols are present you can always try installing from PECL directly or fall back to [compiling from source](https://www.php.net/manual/en/mongodb.installation.manual.php) (optionally specifying `--mongodb-developer-flags` to `configure`). That said, if the segfault is happening in OpenSSL when you're not using the driver directly it's likely that `ext-mongodb` isn't even part of the backtrace, so I'd focus on PHP and OpenSSL for now.

PHP's own docs for GDB backtraces may provide some guidance: https://bugs.php.net/bugs-generating-backtrace.php

Another approach may be to try and reproduce this error through the PHP CLI on your production system (or the [built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php)). If that's possible, it should be easier to test and capture a backtrace than having to go through FPM each time.

**Comment by remicollet** [comment]
Notice: to install the debug information for any package. Usually "gdb" display this command when missing

`dnf debuginfo-install php-cli php-fpm php-pecl-mongodb`

**Comment by remicollet** [comment]
@jmikola for RPM distribution, binaries are never stripped, but debug data moved to a separate package to reduce installation size (most of users don't need them)

**Comment by dadamssg** [comment]
@remicollet thank you!

i was able to do that and now i see this.

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/881986/154263276-a3b55680-3644-493c-b216-d559e0d49fa0.png">


@jmikola looks like my error is coming from 

```
/var/tmp/mongodb/src/libmongoc/src/libmongoc/src/mongoc/mongoc-crypto-openssl.c:51
```

**Comment by remicollet** [comment]
> #2  0x00007f744158ab35 in ssl3_free_digest_list () from /lib64/libssl.so.1.1

Looks like you have **openssl11-libs** installed (and used by libmsodbcsql)
This is terribly wrong, mixing openssl 1.0 and 1.1 in the same process cannot work, and will raise such issue.

Try to remove it.

**Comment by dadamssg** [comment]
I believe `pecl` was used to install some of the extensions. there was no one installing php extensions when this issue arose though which is why I'm perplexed. is there a way to check when a package(openssl11) was installed on my machine? is it in the realm of possibility that anti-virus software or something else would take it upon itself to install that? 

side note: I'm at the hospital with my wife who is having a baby today so I won't be able to do much with this today otherwise I would be quick to respond since I really appreciate you both helping me

**Comment by remicollet** [comment]
@jmikola I notice libmongoc have some internal functions from openssl 1.1 when build with openssl 1.0

=> https://github.com/mongodb/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-crypto-openssl.c#L41

From an objdump
```
000000000008a210 g    DF .text	0000000000000012  Base        EVP_MD_CTX_free
00000000000e05b0 g    DF .text	0000000000000012  Base        EVP_CIPHER_CTX_free
000000000008a200 g    DF .text	000000000000000a  Base        EVP_MD_CTX_new
00000000000e05a0 g    DF .text	000000000000000a  Base        EVP_CIPHER_CTX_new

```

It will be nice to not make such internal functions public, and hide them (ex in above backtrace, you can see that openssl 1.1 call the function from libmongoc, instead of its own implementation, which seems terrible)

**Comment by remicollet** [comment]
> I believe pecl was used to install some of the extensions.

If you use my repo for php, also use it for extensions... [most of them](https://blog.remirepo.net/pages/PECL-extensions-RPM-status) are available.

If think openssl11-devel was badly installed at some time, so build from sources (pecl command) of one ext use it.

>  is there a way to check when a package(openssl11) was installed on my machine? 

rpm -qi  packagename => "Install Date"
also "yum history"

And "yum remove" will tell you is something really need it

**Comment by jmikola** [comment]
> side note: I'm at the hospital with my wife who is having a baby today so I won't be able to do much with this today otherwise I would be quick to respond since I really appreciate you both helping me

Congratulations! Hope everything goes smoothly and I appreciate your patience while we sort this out.

And huge thanks to @remicollet for magically appearing in this thread :)

----

> I notice libmongoc / libmongocrypt have some internal functions from openssl 1.1 when build with openssl 1.0

I agree this is problematic. The intention here was obviously just to polyfill the OpenSSL 1.1 functions but the fact that these are global symbols invites them to be called from places outside of libmongoc, which is certainly a problem.

> ```
> 000000000008a210 g    DF .text	0000000000000012  Base        EVP_MD_CTX_free
> 00000000000e05b0 g    DF .text	0000000000000012  Base        EVP_CIPHER_CTX_free
> 000000000008a200 g    DF .text	000000000000000a  Base        EVP_MD_CTX_new
> 00000000000e05a0 g    DF .text	000000000000000a  Base        EVP_CIPHER_CTX_new
> ```

It looks like these functions originate from _both_ libmongoc and libmongocrypt. I'll file JIRA tickets in both projects to propose we address this (either static declarations or prefixed names, as we do for some libbson polyfills).

**Comment by dadamssg** [comment]
sorry for my ignorance...as far as actions for me to attempt when I am able...is attempting to uninstall openssl11 something that makes sense?
```
yum remove openssl11-devel
```

^ based on remi's reply earlier

**Comment by remicollet** [comment]
> sorry for my ignorance...as far as actions for me to attempt when I am able...is attempting to uninstall openssl11 something that makes sense?
> 
> ```
> yum remove openssl11-devel
> ```
> 
> ^ based on remi's reply earlier

To remove the library, yum remove openssl11-libs 
To remove the devel, yum remove openssl11-devel

Removing the headers will avoid using it, but you will have to reinstall everything build with it
Removing the library will probably break things... btw things are already broken ;)

**Comment by remicollet** [comment]
@jmikola see https://github.com/mongodb/libmongocrypt/pull/251 and https://github.com/mongodb/mongo-c-driver/pull/946

**Comment by jmikola** [comment]
> see https://github.com/mongodb/libmongocrypt/pull/251 and https://github.com/mongodb/mongo-c-driver/pull/946

@remicollet: Thanks for the PRs. I just reported [CDRIVER-4297](https://jira.mongodb.org/browse/CDRIVER-4297) and [MONGOCRYPT-383](https://jira.mongodb.org/browse/MONGOCRYPT-383) and will cross-reference those now.

**Comment by dadamssg** [comment]
lol well I've since disabled the extension so things aren't completely broken. we only use Mongo to store xhprof profiles so that's the only thing not working. 

I'm scared removing openssl11 will cause my semi-functioning setup to break. it seems like `libmsodbcsql` is also using it? we use mssql and this seems like removing that could potentially affect the sql srv driver(odbc)? idk. this stuff is so much more lower level than what I have an understanding for

**Comment by dadamssg** [comment]
@jmikola awesome. thank you!

**Comment by dadamssg** [comment]
@jmikola this release works for us and our situation. thank you so much. really appreciate you digging into this with me.
