### ISSUE TITLE
Wrong PIE extension name

### ISSUE THREAD

**Issue by macintoshplus** [10gen-labs/mongo-php-driver-prototype#1750]
In the file `composer.json` the extension name starts with `ext-`.

https://github.com/mongodb/mongo-php-driver/blob/v1.x/composer.json#L19

According to the php/pie [documentation](https://github.com/php/pie/blob/main/docs/extension-maintainers.md#extension-name), the extension name should not be prefixed with `ext-`.

**Comment by alcaeus** [comment]
We have released 1.20.1 which brings the correct extension name as well as some other fixes for PIE support.
