### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stof** [10gen-labs/mongo-php-driver-prototype#25]
This repo does not have the config to compile the extension on Windows.

Making the extension compatible with Windows seems a must-have to me (even though I'm not using Windows myself anymore)

**Comment by bjori** [comment]
Indeed - we will support Windows in the near future.
Once we put this up on pecl.php.net we will also have automatic windows builds for releases.

We haven't decided if this repo will be merged into the http://pecl.php.net/mongo repo as a 2.0.0 release, or if we will use alternative name.

**Comment by jmikola** [comment]
Tracking this with https://jira.mongodb.org/browse/PHPC-175. Thanks @stof.

**Comment by stof** [comment]
Regarding your second point, see my comment on https://jira.mongodb.org/browse/PHPC-174

Regarding the automatic build on pecl.php.net, this is true only if you provide the config.w32 file. Otherwise, it cannot build on Windows
