### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by ovr** [10gen-labs/mongo-php-driver-prototype#58]
Hey!
Any plans on it?
Thanks

**Comment by bjori** [comment]
Absolutely, yes.
I'm currently working on some issues in the mongo-c-driver (which we are wrapping).
Once we release 1.2.0 of mongo-c-driver I hope to start working on PHP7.

We do not plan on PHP7 integration with the current pecl/mongo driver, so PHP7 for this driver is a high priority

**Comment by ovr** [comment]
Thank you for answer :beers:

**Comment by dmifedorenko** [comment]
Hello. Is where any news about PHP7 support?

Thirst PHP7 RC1 will be released soon, I want try bechmark it on production, but cant do this without mongo support.

**Comment by bjori** [comment]
We won't be able to release it before RC1. Hopefully RC2 maybe?

**Comment by dmifedorenko** [comment]
Any news about PHP7 support? We can test alpha version of mongo driver on our site and give you feedback.

**Comment by bjori** [comment]
RC1 was released two days ago. RC2 is scheduled for 3rd of September. Thats a bit aggressive plan.. But lets see how it goes.

Have you taken a look at pecl/mongodb for PHP5 yet? The PHP7 ext will have the same API so you could work on porting your app over to use the next pecl/mongodb while you wait for the PHP7 support coming soon...

**Comment by dmifedorenko** [comment]
Migration to pecl/mongodb is not problem, we can rewrite code in couple hours.

Will wait first branch with PHP7 support and will check it on unit tests and one of our production nodes in read-only mode. We are exciting of PHP7 performance but cant check it on big data without mongodb support. 

Thank you.

**Comment by bjori** [comment]
Cool :D I'll make sure to poke you when we have something to show for it.
Like I said, we hope to have something around RC2... :)

**Comment by ht-kahn** [comment]
Hi, do we have the mongodb driver for php7, looking for......

**Comment by bjori** [comment]
@ht-kahn See https://github.com/mongodb/mongo-php-driver/pull/136 and https://jira.mongodb.org/browse/PHPC-285

**Comment by jonathanpmartins** [comment]
Like I see in the link, it is in progress yet, love to test it in production. Is the only module that I am waiting for. Thanks for your work!

**Comment by manuelbcd** [comment]
@bjori I can see the progression but this thread is quite old and php7 is not supported by legacy driver as far as I know. Do we have any new on this?

Thank you very much

**Comment by alcaeus** [comment]
@manuelbcd the legacy driver will not support PHP 7. If you are using PHP 7 you'll need to use `ext-mongodb` instead of `ext-mongo`.

**Comment by lackoxygen** [comment]
Write a large number of network requests in one controller，Mongodb can't find data, Also, how can I achieve a disconnection?

**Comment by jmikola** [comment]
@lackoxygen: Your comment doesn't seem related to this thread, which was asking about PHP 7 support (resolved three years ago). Please open a new issue and provide as much information as possible as requested in the new issue template.
