### ISSUE TITLE
BulkWrite Error working with Swoole HTTP Server

### ISSUE THREAD

**Issue by MassiAtZend** [10gen-labs/mongo-php-driver-prototype#925]
The following error 'BulkWrite objects may only be executed once and this instance has already been executed' is generated on every post after the first one (the first does insert data correctly) working with Swoole HTTP server.

The setup is 'docker' based, PHP7.2-cli image, using latest version on the extension and the PHP Library. See below:
_____
php -i 
_____
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
mongodb
libbson bundled version => 1.12.0
libmongoc bundled version => 1.12.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
____________
composer.lock
____________

```
{
            "name": "mongodb/mongodb",
            "version": "1.4.2",
            "source": {
                "type": "git",
                "url": "https://github.com/mongodb/mongo-php-library.git",
                "reference": "bd148eab0493e38354e45e2cd7db59b90fdcad79"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/mongodb/mongo-php-library/zipball/bd148eab0493e38354e45e2cd7db59b90fdcad79",
                "reference": "bd148eab0493e38354e45e2cd7db59b90fdcad79",
                "shasum": ""
            },
            "require": {
                "ext-hash": "*",
                "ext-json": "*",
                "ext-mongodb": "^1.5.0",
                "php": ">=5.5"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.8.36 || ^6.4"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.4.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "MongoDB\\": "src/"
                },
                "files": [
                    "src/functions.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "Apache-2.0"
            ],
            "authors": [
                {
                    "name": "Jeremy Mikola",
                    "email": "jmikola@gmail.com"
                },
                {
                    "name": "Derick Rethans",
                    "email": "github@derickrethans.nl"
                },
                {
                    "name": "Katherine Walker",
                    "email": "katherine.walker@mongodb.com"
                }
            ],
            "description": "MongoDB driver library",
            "homepage": "https://jira.mongodb.org/browse/PHPLIB",
            "keywords": [
                "database",
                "driver",
                "mongodb",
                "persistence"
            ],
            "time": "2018-07-18T14:33:41+00:00"
        },
```

________
Modules
________
[PHP Modules]
Core
ctype
curl
date
dom
event
fileinfo
filter
ftp
hash
iconv
json
libxml
mbstring
mongodb
mysqlnd
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
swoole
tokenizer
uuid
xml
xmlreader
xmlwriter
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

The project installation is done using zend-expressive + zend-expressive-swoole via composer; Swoole HTTP server is run via CLI.
Swoole compiled as follow:

```
    apt-get install -y --no-install-recommends \
    libhiredis0.13 libnghttp2-14 libhiredis-dev libnghttp2-dev && \
    cd /tmp && \
    git clone https://github.com/swoole/swoole-src.git swoole && \
	( \
		cd swoole \
		&& phpize \
		&& ./configure --enable-sockets --enable-async-redis --enable-openssl --enable-http2 --enable-swoole \
		&& make -j$(nproc) \
		&& make install \
	) && \
	docker-php-ext-install /tmp/swoole && \
    rm -r /tmp/swoole
```

The write model use is attached.
[SavePdfDocument.txt](https://github.com/mongodb/mongo-php-driver/files/2382517/SavePdfDocument.txt)

If necessary I can upload an archive of the entire project code.

**Comment by jmikola** [comment]
> The following error 'BulkWrite objects may only be executed once and this instance has already been executed' is generated on every post after the first one (the first does insert data correctly) working with Swoole HTTP server.

Looking at `SavePdfDocument.txt`, you're constructing a single BulkWrite instance in the constructor and  each invocation of `save()` will add an insert operation to it (calling `BulkWrite::insert()`) and then execute the bulk write via `Manager::executeBulkWrite()`. If your application is calling `save()` more than once on a single SavePdfDocument object, then this exception is entirely expected.

Note the internal state of a BulkWrite is not reset after execution. Once a write operation is added it remains in the object for its lifetime.

While the exception message is quite clear, I realize that the [`MongoDB\Driver\BulkWrite`](http://php.net/manual/en/class.mongodb-driver-bulkwrite.php) and [`MongoDB\Driver\Manager::executeBulkWrite()`](http://php.net/manual/en/mongodb-driver-manager.executebulkwrite.php) don't actually note that BulkWrite instances can only be executed a single time. I've opened [PHPC-1269](https://jira.mongodb.org/browse/PHPC-1269) to track that improvement.

**Comment by MassiAtZend** [comment]
Thanks a lot for the thorough explanation, it is definitely due to some caching optimization the Swoole extension applies.
